# Copyright 2026 Cloudera, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# Lookup AI agent in project for AMP deployments
- name: Verify AI agent deployment for AMP deployments
  when: cai_ai_studio_amp_deployment
  block:
    - name: Check for existing AI Studios
      ansible.builtin.uri:
        url: "{{ cai_workspace_api }}/api/v1/projects/{{ cai_user }}/{{ cai_project }}/composable-accelerators"
        method: GET
        user: "{{ cai_workbench_api_key }}"
        password: ''
        force_basic_auth: yes
        validate_certs: "{{ cai_endpoint_tls }}"
      register: __studio_info

    - name: Extract existing AI Studio details
      ansible.builtin.set_fact:
        __existing_studio: "{{ (__studio_info.json | selectattr('slug', 'match', cai_ai_studio_override['slug']) | first) | default([]) }}"

    # Assert that the AI Studio exists
    - name: Assert that the AI Studio exists and is ready
      ansible.builtin.assert:
        that:
          - __existing_studio | length > 0
          - __existing_studio.status in ['running', 'success']
        fail_msg: "AI Studio '{{ cai_ai_studio_override.slug }}' does not exist and no details provided to create it"
        success_msg: "AI Studio '{{ cai_ai_studio_override.slug }}' exists or will be created"

# Get APP_SUBDOMAIN
- name: Get all Applications within the Project
  cloudera.services.ml_project_application_info:
    endpoint: "{{ cai_workspace_api }}"
    api_key: "{{ cai_workbench_api_key }}"
    endpoint_tls: "{{ cai_endpoint_tls }}"
    project_name: "{{ cai_project }}"
  register: __ml_app_info

- name: Find the Application Details for the Studio
  ansible.builtin.set_fact:
    __studio_application_subdomain: "{{ (__ml_app_info.applications | selectattr('name', 'equalto', cai_ai_studio_override['application_name']) | map(attribute='subdomain') | first) }}"

# Create the LLM model
- name: List Current Registered LLM Models
  ansible.builtin.uri:
    url: "https://{{ __studio_application_subdomain }}.{{ cai_workspace_api | replace('https://', '') }}/api/grpc/listModels"
    method: POST
    headers:
      Authorization: Bearer {{ cai_workbench_api_key }}
      content-type: application/json
    body_format: json
    body: {}
    validate_certs: "{{ cai_endpoint_tls }}"
  register: __llm_models_info

- name: Register LLM Model with AI Studio
  when: "__llm_models_info.json.model_details | selectattr('model_name', 'equalto', llm_model_item.model_name) | list | length == 0"
  ansible.builtin.uri:
    url: "https://{{ __studio_application_subdomain }}.{{ cai_workspace_api | replace('https://', '') }}/api/grpc/addModel"
    method: POST
    headers:
      Authorization: Bearer {{ cai_workbench_api_key }}
      content-type: application/json
    body_format: json
    body:
      model_name: "{{ llm_model_item.model_name }}"
      model_type: "{{ llm_model_item.model_type }}"
      provider_model: "{{ llm_model_item.provider_model }}"
      api_key: "{{ llm_model_item.api_key | default(omit) }}"
      api_base: "{{ llm_model_item.api_base | default(omit) }}"
      aws_region_name: "{{ llm_model_item.aws_region_name | default(omit) }}"
      aws_access_key_id: "{{ llm_model_item.aws_access_key_id | default(omit) }}"
      aws_secret_access_key: "{{ llm_model_item.aws_secret_access_key | default(omit) }}"
    validate_certs: "{{ cai_endpoint_tls }}"
  loop_control:
    loop_var: llm_model_item
  loop: "{{ llm_model_details }}"
  register: __llm_model_register

- name: Set Model as Default for AI Studio
  when:
    - item.json.model_id is defined
    - llm_model_item.llm_model_item.default
  ansible.builtin.uri:
    url: "https://{{ __studio_application_subdomain }}.{{ cai_workspace_api | replace('https://', '') }}/api/grpc/setStudioDefaultModel"
    method: POST
    headers:
      Authorization: Bearer {{ cai_workbench_api_key }}
      content-type: application/json
    body_format: json
    body:
      model_id: "{{ llm_model_item.json.model_id | default((__llm_models_info.json.model_details | selectattr('model_name', 'equalto', llm_model_item.llm_model_item.model_name) | first).model_id) }}"
    validate_certs: "{{ cai_endpoint_tls }}"
    loop: "{{ __llm_model_register.results }}"
