# Copyright 2026 Cloudera, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

cai_workspace_api: "{{ undef(hint='Please define CAI Workbench API endpoint') }}"
cai_workbench_api_key: "{{ undef(hint='Please define CAI Workbench API key') }}"
cai_project: "{{ undef(hint='Please define CAI Project name') }}"

cai_user: "{{ undef(hint='Please define CAI Username') }}"

cai_runtime_image_name: "{{ undef(hint='Please define the runtime Image to use for the AI Studio') }}"
cai_environment_variables: {}
cai_runtime_addons: []
cai_task_level_runtimes: []

cai_ai_studio_async_setup: false

cai_ai_studio_details: "{{ _cai_ai_studios[ai_studio] }}"

ai_studio: "agent_studio"
