---
- name: Discover the Agent Studio runtime
  cloudera.services.ml_runtimes_info:
    endpoint: "{{ cai_workspace_api }}"
    api_key: "{{ cai_workbench_api_key }}"
    endpoint_tls: "{{ cai_endpoint_tls }}"
    edition: Agent Studio
    editor: "PBJ Workbench"
    kernel: "Agent Studio"
  register: __agent_studio_runtime
  until: __agent_studio_runtime.runtimes | length > 0
  retries: 12
  delay: 10
  failed_when: false

- name: Set fact for runtime id
  ansible.builtin.set_fact:
    __runtime_id: "{{ __agent_studio_runtime.runtimes | selectattr('full_version', 'eq', runtime_version) | map(attribute='image_identifier') | first }}"
  vars:
    runtime_version: "{{ __agent_studio_runtime.runtimes | map(attribute='full_version') | community.general.version_sort(reverse=True) | first }}"

- name: Start Agent Studio application
  cloudera.services.ml_project_application:
    endpoint: "{{ cai_workspace_api }}"
    api_key: "{{ cai_workbench_api_key }}"
    endpoint_tls: "{{ cai_endpoint_tls }}"
    project_name: "{{ cai_project }}"
    name: "{{ cai_agent_studio_app_name }}"
    script: "{{ cai_agent_studio_script }}"
    auth: "{{ cai_agent_studio_app_auth }}"
    subdomain: "{{ cai_agent_studio_subdomain }}"
    env: "{{ cai_agent_studio_environment | default(omit) }}"
    runtime: "{{ __runtime_id }}"
    cpu: "{{ cai_agent_app_cpu }}"
    memory: "{{ cai_agent_app_memory }}"
    state: present
  # vars:
  #   runtime_version: "{{ __agent_studio_runtime.runtimes | map(attribute='full_version') | community.general.version_sort(reverse=True) | first }}"
  #   job_runtime: "{{ __agent_studio_runtime.runtimes | selectattr('full_version', 'eq', runtime_version) | map(attribute='image_identifier') | first }}"

- name: Poll until the Agent Studio application is running
  when: not cai_ai_studio_async_setup
  cloudera.services.ml_project_application_info:
    project_name: "{{ cai_project }}"
    endpoint: "{{ cai_workspace_api }}"
    api_key: "{{ cai_workbench_api_key }}"
    endpoint_tls: "{{ cai_endpoint_tls }}"
  register: __app_info
  until: >
    __app_info.applications |
    selectattr('name', 'equalto', cai_agent_studio_app_name) |
    selectattr('subdomain', 'equalto', cai_agent_studio_subdomain) |
    selectattr('status', 'equalto', 'APPLICATION_RUNNING') |
    list | length > 0
  retries: 30
  delay: 10
  failed_when: false
