# Copyright 2026 Cloudera, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# Validate required variables based on AI Studio mode
- name: Assert required variables for AI Studios Enabled Mode
  when: cai_ai_studio_mode_enabled
  ansible.builtin.assert:
    that:
      - cai_user is defined
      - cai_agent_studio_slug is defined
      - cai_agent_studio_git_url is defined
      - cai_agent_studio_git_ref is defined
    fail_msg: "When cai_ai_studio_mode_enabled is true, the following variables must be defined: cai_user, cai_agent_studio_slug, cai_agent_studio_git_url, cai_agent_studio_git_ref"
    quiet: no

- name: Assert required variables for AI Studios Disabled Mode
  when: not cai_ai_studio_mode_enabled
  ansible.builtin.assert:
    that:
      - cai_agent_studio_app_name is defined
      - cai_agent_studio_script is defined
      - cai_agent_studio_subdomain is defined
      - cai_agent_app_cpu is defined
      - cai_agent_app_memory is defined
    fail_msg: "When cai_ai_studio_mode_enabled is false, the following variables must be defined: cai_agent_studio_app_name, cai_agent_studio_script, cai_agent_studio_subdomain, cai_agent_app_cpu, cai_agent_app_memory"
    quiet: no

# Retrieve details of the Cloudera AI project
- name: Get details on {{ cai_project }}
  cloudera.services.ml_project_info:
    endpoint: "{{ cai_workspace_api }}"
    name: "{{ cai_project }}"
    api_key: "{{ cai_workbench_api_key }}"
    endpoint_tls: "{{ cai_endpoint_tls }}"
  register: __cai_project_details

# Register AI Agent Studio runtime repo
# ....First check if Agent Studio runtime repository exists
- name: Check for existing Agent Studio runtime repository
  ansible.builtin.uri:
    url: "{{ cai_workspace_api }}/api/v2/runtimerepos?search_filter={{ query_parameters | to_json | urlencode }}"
    method: GET
    headers:
      Accept: application/json
      Authorization: "Bearer {{ cai_workbench_api_key }}"
    status_code: [200]
    validate_certs: "{{ cai_endpoint_tls }}"
  vars:
    query_parameters:
      name: "{{ cai_agent_studio_runtime_name }}"
  register: __runtime_repo_check

# ...Then create Agent Studio runtime repository if it doesn't exist
- name: Create Agent Studio runtime repository
  ansible.builtin.uri:
    url: "{{ cai_workspace_api }}/api/v2/runtimerepos"
    method: POST
    headers:
      Accept: application/json
      Authorization: "Bearer {{ cai_workbench_api_key }}"
      Content-Type: application/json
    body_format: json
    body:
      name: "{{ cai_agent_studio_runtime_name }}"
      url: "{{ cai_agent_studio_runtime_repo_url }}"
    status_code: [200, 201, 409]  # 409 in case repository already exists
    validate_certs: "{{ cai_endpoint_tls }}"
  when: __runtime_repo_check.json.runtimerepos | length == 0
  register: __runtime_repo_creation_result

# ...Finally pull/sync runtime repositories
- name: Pull Agent Studio runtime repository
  ansible.builtin.uri:
    url: "{{ cai_workspace_api }}/api/v1/runtime-repos/pull-request"
    method: POST
    headers:
      Content-Type: application/json
    user: "{{ cai_workbench_api_key }}"
    password: ''
    force_basic_auth: yes
    body_format: json
    body: {}
    status_code: [200, 202, 204]
    validate_certs: "{{ cai_endpoint_tls }}"
  # when: __runtime_repo_check.json.runtimerepos | length == 0 or __runtime_repo_creation_result is defined
  register: __runtime_repo_pull_result

- name: Launch Agent Studio in AI Studios  Enabled Mode
  when: cai_ai_studio_mode_enabled
  ansible.builtin.include_tasks: ai_studio_mode_enabled.yml

- name: Launch Agent Studio in AI Studios Disabled Mode
  when: not cai_ai_studio_mode_enabled
  ansible.builtin.include_tasks: ai_studio_mode_disabled.yml
