# Copyright 2026 Cloudera, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Get details on {{ cai_project }}
  cloudera.services.ml_project_info:
    endpoint: "{{ cai_workspace_api }}"
    name: "{{ cai_project }}"
    api_key: "{{ cai_workbench_api_key }}"
    endpoint_tls: "{{ cai_endpoint_tls }}"
  register: __cai_project_details

# Lookup AI agent in project for AMP deployments
- name: Verify AI agent deployment for AMP deployments
  when: cai_ai_studio_amp_deployment
  block:
    # Lookup AI agent in project
    - name: Check for existing AI Studios
      ansible.builtin.uri:
        url: "{{ cai_workspace_api }}/api/v1/projects/{{ cai_user }}/{{ cai_project }}/composable-accelerators"
        method: GET
        user: "{{ cai_workbench_api_key }}"
        password: ''
        force_basic_auth: yes
        validate_certs: "{{ cai_endpoint_tls }}"
      register: __studio_info

    - name: Extract existing AI Studio details
      ansible.builtin.set_fact:
        __existing_studio: "{{ (__studio_info.json | selectattr('slug', 'match', cai_ai_studio_override['slug']) | first) | default([]) }}"

    # Assert that the AI Studio exists
    - name: Assert that the AI Studio exists and is ready
      ansible.builtin.assert:
        that:
          - __existing_studio | length > 0
          - __existing_studio.status in ['running', 'success']
        fail_msg: "AI Studio '{{ cai_ai_studio_override.slug }}' does not exist and no details provided to create it"
        success_msg: "AI Studio '{{ cai_ai_studio_override.slug }}' exists"

# Get APP_SUBDOMAIN
- name: Get all Applications within the Project
  cloudera.services.ml_project_application_info:
    endpoint: "{{ cai_workspace_api }}"
    api_key: "{{ cai_workbench_api_key }}"
    endpoint_tls: "{{ cai_endpoint_tls }}"
    project_name: "{{ cai_project }}"
  register: __ml_app_info

- name: Find the Application Details for the Studio
  ansible.builtin.set_fact:
    __studio_application_subdomain: "{{ (__ml_app_info.applications | selectattr('name', 'equalto', cai_ai_studio_override['application_name']) | map(attribute='subdomain') | first) }}"

# Get Current Workflow Templates
- name: List Current Workflow Templates
  ansible.builtin.uri:
    url: "https://{{ __studio_application_subdomain }}.{{ cai_workspace_api | replace('https://', '') }}/api/grpc/listWorkflowTemplates"
    method: POST
    headers:
      Authorization: Bearer {{ cai_workbench_api_key }}
      content-type: application/json
    body_format: json
    body: {}
    validate_certs: "{{ cai_endpoint_tls }}"
  register: __workflow_template_info

- name: Upload the Workflow Template file
  when: "__workflow_template_info.json.workflow_templates | selectattr('name', 'equalto', workflow_template_item.template_name) | list | length == 0"
  ansible.builtin.command: 'curl {{ "--insecure" if not cai_endpoint_tls else "" }} -X PUT -H "Authorization: Bearer {{ cai_workbench_api_key }}" -H "Content-Type: multipart/form-data" -F "{{ workflow_template_item.file | basename }}=@{{ workflow_template_item.file }}" {{ cai_workspace_api }}/api/v2/projects/{{ __cai_project_details.projects[0].id }}/files'
  loop_control:
    loop_var: workflow_template_item
  loop: "{{ workflow_templates }}"

# Import Workflow Template if they don't already exist
- name: Import Workflow Templates for AI Studio
  when: "__workflow_template_info.json.workflow_templates | selectattr('name', 'equalto', workflow_template_item.template_name) | list | length == 0"
  ansible.builtin.uri:
    url: "https://{{ __studio_application_subdomain }}.{{ cai_workspace_api | replace('https://', '') }}/api/grpc/importWorkflowTemplate"
    method: POST
    headers:
      Authorization: Bearer {{ cai_workbench_api_key }}
      content-type: application/json
    body_format: json
    body:
      file_path: "{{ [workflow_template_upload_path, workflow_template_item.file | basename] | path_join }}"
    validate_certs: "{{ cai_endpoint_tls }}"
  loop_control:
    loop_var: workflow_template_item
  loop: "{{ workflow_templates }}"
  register: __workflow_templates_register
