# Copyright 2026 Cloudera, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Check for existing AI Studios
  ansible.builtin.uri:
    url: "{{ cai_workspace_api }}/api/v1/projects/{{ cai_user }}/{{ cai_project }}/composable-accelerators"
    method: GET
    user: "{{ cai_workbench_api_key }}"
    password: ''
    force_basic_auth: yes
  register: __studio_info

- name: Extract existing AI Studio details
  ansible.builtin.set_fact:
    __existing_studio: "{{ (__studio_info.json | selectattr('slug', 'match', cai_ai_studio_details['slug']) | first) | default([]) }}"

- name: Launch the AI Studio if required
  when: (__existing_studio | length == 0 or
        __existing_studio.status not in ['configuration', 'running', 'success'])
  ansible.builtin.uri:
    url: "{{ cai_workspace_api }}/api/v1/projects/{{ cai_user }}/{{ cai_project }}/composable-accelerators"
    method: POST
    status_code:
      - 200
      - 201
    user: "{{ cai_workbench_api_key }}"
    password: ''
    force_basic_auth: yes
    body_format: json
    body:
      name: "{{ cai_ai_studio_details.name }}"
      slug: "{{ cai_ai_studio_details.slug }}"
      gitUrl: "{{ cai_ai_studio_details.git_url }}"
      gitRef: "{{ cai_ai_studio_details.git_ref }}"
  register: __studio_launch

- name: Find available runtimes
  ansible.builtin.uri:
    url: "{{ cai_workspace_api }}/api/v1/runtimes/?includeAll=true"
    method: GET
    user: "{{ cai_workbench_api_key }}"
    password: ''
    force_basic_auth: yes
  register: __runtimes_info

- name: Set the AI Studio and Runtime ID
  ansible.builtin.set_fact:
    __studio_deployment_id: "{{ __studio_launch.json.id | default(__existing_studio.id) }}"
    __runtime_id: "{{ (__runtimes_info.json['runtimes'] | selectattr('imageIdentifier', 'match', cai_runtime_image_name)) | map(attribute='id') | first }}"

- name: Configure the AI Studio
  when: (__existing_studio | length == 0 or
        __existing_studio.status not in ['running', 'success'])
  ansible.builtin.uri:
    url: "{{ cai_workspace_api }}/api/v1/projects/{{ cai_user }}/{{ cai_project }}/composable-accelerators/{{ __studio_deployment_id }}/configure"
    method: POST
    status_code:
      - 200
      - 201
    user: "{{ cai_workbench_api_key }}"
    password: ''
    force_basic_auth: yes
    body_format: json
    body: >
      {
        "engineImageRuntimeId": {{ __runtime_id | int }},
        "runImportTasks": {{ cai_ai_studio_details.run_import_tasks | lower }},
        "environmentVariables": {{ cai_environment_variables | to_json }},
        "runtimeAddons": {{ cai_runtime_addons }},
        "taskLevelRuntimes": {{ cai_task_level_runtimes }}
      }
  register: __studio_configure

- name: Polling until AI Studio configuration has completed
  when: not cai_ai_studio_async_setup
  ansible.builtin.uri:
    url: "{{ cai_workspace_api }}/api/v1/projects/{{ cai_user }}/{{ cai_project }}/composable-accelerators/{{ __studio_deployment_id }}"
    method: GET
    user: "{{ cai_workbench_api_key }}"
    password: ''
    force_basic_auth: yes
  register: __studio_status
  retries: 60
  delay: 30
  until: "__studio_status.json['status'] == 'success'"
