---

# Copyright 2026 Cloudera, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Validate API Documentation

on:
  pull_request:
  workflow_dispatch:

env:
  HATCH_DATA_DIR: ~/.hatch

jobs:
  validate-docs:
    name: Validate API documentation
    runs-on: ubuntu-latest
    steps:
      - name: Configure Ansible collections path
        id: vars
        uses: actions/github-script@v9
        with:
          script: |
            name = process.env.GITHUB_REPOSITORY.split('/')[1]
            path = name.replace('.', '/')

            core.exportVariable('ANSIBLE_COLLECTIONS_PATH', process.env.GITHUB_WORKSPACE)

            const checkoutPath = `ansible_collections/${path}`
            core.setOutput('checkout-path', checkoutPath)

      - name: Checkout project into Ansible collections path
        uses: actions/checkout@v6
        with:
          path: ${{ steps.vars.outputs.checkout-path }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install Hatch
        run: pip install hatch
     
      - name: Cache Hatch virtual environments
        uses: actions/cache@v6
        with:
          path: ${{ env.HATCH_DATA_DIR }}
          key: hatch-${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }} # '**/hatch.lock' when hatch.lock is supported
          restore-keys: |
            hatch-${{ runner.os }}-

      - name: Render API documentation
        run: hatch run docs:render
        working-directory: ${{ steps.vars.outputs.checkout-path }}

      - name: Upload antsibull-doc log artifact
        if: always()
        uses: actions/upload-artifact@v7
        with:
          path: ${{ steps.vars.outputs.checkout-path }}/antsibull.log
          name: antsibull-${{ github.sha }}.log
          retention-days: 7 
